### ISSUE TITLE
Part of Speech

### ISSUE THREAD

**Issue by JasonLin43212** [dhmit/lang_learn#5]
We want functions which utilize NLTK to get all the nouns, verbs, adjectives, etc from a piece of text.

- [x] Make GAT a dependency in our project
- [x] Noun Parser (Justice)
- [x] Verb Parser (LJ)
- [x] Adjective Parser (Shara)
- [x] Adverb/Article Parser (Jason)

Weird bug with apostrophe s

**Comment by ryaanahmed** [comment]
Check out work over in the Gender Analysis Toolkit: https://github.com/dhmit/gender_analysis/blob/master/gender_analysis/analysis/dependency_parsing.py

We may actually just want to make GAT one of our dependencies for this project.

**Comment by ryaanahmed** [comment]
Closed via #7 and #6
